=== Hawthorne001/metadata/schemas/featured-pools.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://balancer.fi/featured-pools.json",
  "title": "Featured pools",
  "description": "Featured pools",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "chainId": {
        "type": "number"
      },
      "imageUrl": {
        "type": "string"
      },
      "primary": {
        "type": "boolean"
      }
    },
    "required": ["id", "description", "chainId", "imageUrl"]
  }
}

=== Hawthorne001/metadata/pools/featured.json
[
    {
        "id": "0x8207c7541ce31b38dbd46890f2a832cf1ef7c512",
        "imageUrl": "https://v3.balancer.fi/images/chains/HYPEREVM.svg",
        "chainId": 999,
        "primary": true,
        "description": "Balancer v3 on HyperEVM"
    },
    {
        "id": "0x85b2b559bc2d21104c4defdd6efca8a20343361d",
        "imageUrl": "https://v3.balancer.fi/images/chains/MAINNET.svg",
        "chainId": 1,
        "description": "100% boosted USD pool"
    },
    {
        "id": "0x19aeb8168d921bb069c6771bbaff7c09116720d0",
        "imageUrl": "https://v3.balancer.fi/images/chains/BASE.svg",
        "chainId": 8453,
        "description": "New reCLAMM pool on Base"
    }
]
