=== Hawthorne001/metadata/schemas/hooks.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://balancer.fi/hooks.json",
  "title": "Hook",
  "description": "A hook that can be added to a pool",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "learnMore": {
        "type": "string"
      },
      "addresses": {
        "type": "object",
        "patternProperties": {
          "^[0-9]+$": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "required": ["id", "name", "description", "addresses"]
  }
}

=== Hawthorne001/metadata/hooks/index.json
[
    {
        "id": "hooks_exitfee",
        "name": "Exitfee Hook",
        "description": "The exit fee hook",
        "addresses": {
            "11155111": ["0x2Aa9D4066DAe16ef001765efF2cA8F41Bde0b019"]
        }
    },
    {
        "id": "hooks_feetaking",
        "name": "Feetaking Hook",
        "description": "The fee taking hook",
        "addresses": {
            "11155111": ["0x790ae803b6c0467C6A4cbDc6d6d712DE34CfdB76"]
        }
    },
    {
        "id": "hooks_stablesurge",
        "name": "StableSurge Hook",
        "description": "The StableSurge Hook",
        "addresses": {
            "11155111": ["0x1adc55adb4caae71abb4c33f606493f4114d2091"]
        }
    }
]
